//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWARF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWARF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;DWARF Debug Tool&lt;/title&gt;
        ///
        ///    &lt;link href=&apos;http://fonts.googleapis.com/css?family=Droid+Sans+Mono&apos; rel=&apos;stylesheet&apos; type=&apos;text/css&apos;&gt;
        ///
        ///    &lt;style&gt;
        ///        * {
        ///            margin:0;
        ///            padding:0;
        ///        }
        ///
        ///        body {
        ///            font-family: /*&quot;Segoe UI Light&quot;, */&quot;Segoe UI&quot;, Arial, sans-serif;
        ///            color: #333;
        ///        }
        ///
        ///        .gray {
        ///            color: rgb(128, 128, 128);
        ///            margin-top:3px;
        ///        }
        ///
        ///        #console-messages {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string debug_html {
            get {
                return ResourceManager.GetString("debug_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.defineProperty(window, &apos;__line&apos;, {
        ///    get: function () {
        ///        return __stack[__stack.length - 2].getLineNumber();
        ///    }
        ///});
        ///
        ///var DebugHelper = {
        ///
        ///    // This should only be called when an error or warning occurs ( or any consolemessage that isn&apos;t called from console.log() )
        ///
        ///	notifyConsoleMessage: function(formname, eventname, linenumber, message, sourcefile, responseType, messageType) {
        ///        App.invokeOnFormAsync(&quot;debug&quot;, &quot;addConsoleMessageToList(&apos;&quot; + formname + &quot;&apos;, &apos;&quot; + eventname  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string debug_js {
            get {
                return ResourceManager.GetString("debug_js", resourceCulture);
            }
        }
    }
}
